### ISSUE TITLE
Does not seem to work with the latest version of BS

### ISSUE THREAD

**Issue by waaadim** [rokucommunity/bsc-plugin-auto-findnode#6]
Getting an error when running this with Brighterscript alpha-41

```
[04:19:12:414 PM] Building
[04:19:12:415 PM] Error when calling plugin bsc-plugin-findnodes.beforeBuildProgram: TypeError: program.getScopes is not a function or its return value is not iterable
    at findNodeWithIDInjection (.../node_modules/bsc-plugin-auto-findnode/src/findNodes.ts:20:33)
    at Plugin.beforeProgramTranspile (.../node_modules/bsc-plugin-auto-findnode/src/Plugin.ts:15:32)
    at .../node_modules/brighterscript/src/PluginInterface.ts:83:51
    at Logger.time (.../node_modules/@rokucommunity/logger/dist/Logger.js:355:20)
    at PluginInterface.emitAsync (.../node_modules/brighterscript/src/PluginInterface.ts:81:40)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.action (.../node_modules/brighterscript/src/Program.ts:1633:27)
    at async Program.build (.../node_modules/brighterscript/src/Program.ts:1630:9)
    at async .../node_modules/brighterscript/src/ProgramBuilder.ts:444:17
    at async .../node_modules/brighterscript/src/ProgramBuilder.ts:442:13
[04:19:12:476 PM] Building finished. (61.873ms)
```

**Comment by waaadim** [comment]
I looked a little bit into this today.

Does it make sense to find all usages of `m.FIELD` and only add those in `init`?
Or is it too risky?

**Comment by TwitchBronBron** [comment]
Hmm. I think it might be too risky to do it that way out of the box. Consider logic like this:

```
m.labelPrimary = m.top.findNode("labelPrimary")
m.labelSecondary = m.top.findNode("labelSecondary")

' m.theme contains "Primary" or "Secondary"
label = m["label" + m.theme]
```

Would technically be a breaking change to make that the default setting. However, I could see there being a configuration option that would apply this optimization. We'd scan for all files in the current scope, build every `m.*` reference, and any that are nodes with those ids, we'd include.

I kinda like this!

**Comment by TwitchBronBron** [comment]
Closing this issue as we've begun cutting v1.0.0-alpha releases that support brighterscript v1 alphas.
